CREATE PROCEDURE ENFAZLA_URUNKATEGORISI
AS
SELECT TOP 1 TBLKATEGORÝ.AD FROM TBLURUN
INNER JOIN TBLKATEGORÝ ON TBLKATEGORÝ.ID=TBLURUN.KATEGORI
GROUP BY TBLKATEGORÝ.AD ORDER BY COUNT(*) DESC

EXEC ENFAZLA_URUNKATEGORISI