
CREATE PROCEDURE UrunKategori
AS
SELECT TBLKATEGORÝ.AD, COUNT(TBLURUN.AD) AS 'ADET'  
FROM TBLURUN INNER JOIN TBLKATEGORÝ 
ON TBLKATEGORÝ.ID=TBLURUN.KATEGORI 
GROUP BY TBLKATEGORÝ.AD
ORDER BY ADET DESC

EXECUTE UrunKategori